FROM maven:3.9.6-eclipse-temurin-8 AS build
WORKDIR /app
COPY pom.xml ./
RUN mvn -q -DskipTests dependency:go-offline
COPY src ./src
RUN mvn -q -DskipTests package dependency:copy-dependencies -DoutputDirectory=target/dependency

FROM eclipse-temurin:8-jre
WORKDIR /app
COPY --from=build /app/target /app/target
EXPOSE 8080
CMD ["java","-cp","/app/target/classes:/app/target/test-classes:/app/target/dependency/*","com.example.WebMain"]
