package com.example.game.model;

import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

// tests generated by ℍ𝕒𝕥𝕤𝕦𝕟𝕖 𝕄𝕚𝕜𝕦 then manually modified
public class GameSquareDetectionTest {

    private Game game;

    @BeforeEach
    void setUp() {
        game = new Game(5, "user", 'w', "comp", 'b');
    }
    
    // ========== ТЕСТЫ НА ОТСУТСТВИЕ КВАДРАТОВ ==========
    
    @Test
    void testNoSquare_EmptyBoard() {
        // Пустая доска - нет квадратов
        char[][] emptyBoard = {
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'}
        };
        game.getBoard().setGrid(emptyBoard);
        assertTrue(game.getBoard().checkWin() == null);
    }
    
    @Test
    void testNoSquare_SinglePiece() {
        // Одна фишка - нет квадратов
        char[][] singlePiece = {
            {'w', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'}
        };
        game.getBoard().setGrid(singlePiece);
        assertTrue(game.getBoard().checkWin() == null);
    }
    
    @Test
    void testNoSquare_TwoPieces() {
        // Две фишки - нет квадратов
        char[][] twoPieces = {
            {'w', 'w', '.', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'}
        };
        game.getBoard().setGrid(twoPieces);
        assertTrue(game.getBoard().checkWin() == null);
    }
    
    @Test
    void testNoSquare_ThreePieces() {
        // Три фишки - нет квадратов
        char[][] threePieces = {
            {'w', 'w', '.', '.', '.'},
            {'w', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'}
        };
        game.getBoard().setGrid(threePieces);
        assertTrue(game.getBoard().checkWin() == null);
    }
    
    @Test
    void testNoSquare_MixedColors() {
        // Фишки разных цветов - нет квадрата
        char[][] mixedColors = {
            {'w', 'b', '.', '.', '.'},
            {'w', 'b', '.', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'}
        };
        game.getBoard().setGrid(mixedColors);
        assertTrue(game.getBoard().checkWin() == null);
    }
    
    @Test
    void testNoSquare_IncompleteSquare() {
        // Неполный квадрат - нет квадрата
        char[][] incompleteSquare = {
            {'w', 'w', 'b', '.', '.'},
            {'w', '.', 'b', '.', '.'},
            {'.', '.', 'b', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'}
        };
        game.getBoard().setGrid(incompleteSquare);
        assertTrue(game.getBoard().checkWin() == null);
    }

    @Test
    void testNoSquare_DiagonalPieces() {
        // Три фишки по диагонали — нет квадрата
        char[][] diagonalPieces = {
            {'w', '.', '.', '.', '.'},
            {'.', 'b', '.', '.', '.'},
            {'.', '.', 'w', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'}
        };
        game.getBoard().setGrid(diagonalPieces);
        assertTrue(game.getBoard().checkWin() == null);
    }
    
    // ========== ТЕСТЫ НА НАЛИЧИЕ КВАДРАТОВ ==========

    @Test
    void testSquare_Rotated45Degrees() {
        // Квадрат повернут на 45° (ромб)
        // координаты вершин: (1,0),(2,1),(1,2),(0,1)
        char[][] rotatedSquare = {
            {'.', 'w', '.', 'b', '.'},
            {'w', '.', 'w', 'b', '.'},
            {'.', 'w', '.', 'b', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'}
        };
        game.getBoard().setGrid(rotatedSquare);
        assertTrue(game.getBoard().checkWin() == 'w');
    }
    
    @Test
    void testSquare_justSquare() {
        // Квадрат
        // w w
        // w w
        char[][] square = {
            {'w', 'w', 'b', 'b', '.'},
            {'w', 'w', 'b', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'}
        };
        game.getBoard().setGrid(square);
        assertTrue(game.getBoard().checkWin() == 'w');
    }
    
    @Test
    void testSquare_AtBoardEdge() {
        // Квадрат у края доски
        char[][] edgeSquare = {
            {'w', 'w', 'b', '.', '.'},
            {'w', 'w', 'b', '.', '.'},
            {'.', '.', 'b', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'}
        };
        game.getBoard().setGrid(edgeSquare);
        assertTrue(game.getBoard().checkWin() == 'w');
    }
    
    @Test
    void testSquare_CenterOfBoard() {
        // Квадрат в центре доски
        char[][] centerSquare = {
            {'.', '.', '.', '.', '.'},
            {'.', 'w', 'w', 'b', '.'},
            {'.', 'w', 'w', 'b', '.'},
            {'.', '.', '.', 'b', '.'},
            {'.', '.', '.', '.', '.'}
        };
        game.getBoard().setGrid(centerSquare);
        assertTrue(game.getBoard().checkWin() == 'w');
    }
    
    @Test
    void testSquare_BlackPieces() {
        // Квадрат из черных фишек
        char[][] blackSquare = {
            {'b', 'b', 'w', 'w', '.'},
            {'b', 'b', 'w', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'},
            {'.', '.', '.', '.', '.'}
        };
        game.getBoard().setGrid(blackSquare);
        assertTrue(game.getBoard().checkWin() == 'b');
    }
}